import { useSearchParams, Link } from 'react-router-dom';
import { useState, useEffect } from 'react';
import type { ActiveBuild, BuildComponent } from '../hooks/useAIAssistant';

// ─── DB lookup types ───────────────────────────────────────────────────────────

interface DbLookupResult {
  name: string;
  category: string;
  specs: Record<string, string | number>;
}

type VerificationSource = 'db' | 'ai';

// ─── Helpers ───────────────────────────────────────────────────────────────────

function decodeBuild(raw: string | null): ActiveBuild | null {
  if (!raw) return null;
  try {
    return JSON.parse(decodeURIComponent(atob(raw))) as ActiveBuild;
  } catch {
    return null;
  }
}

function buildToText(build: ActiveBuild): string {
  const LABELS: [keyof ActiveBuild, string][] = [
    ['cpu', 'CPU'], ['gpu', 'GPU'], ['motherboard', 'Motherboard'],
    ['ram', 'RAM'], ['psu', 'Power Supply'],
  ];
  const lines = [
    '══════════════════════════════════════',
    '  NEUROBUILDS — SHARED PC BUILD',
    '══════════════════════════════════════',
    '',
  ];
  let total = 0;
  for (const [key, label] of LABELS) {
    const c = build[key];
    if (!c) continue;
    lines.push(`${label}: ${c.name}`);
    if (c.price !== undefined) { lines.push(`  Price: $${c.price.toLocaleString()}`); total += c.price; }
    if (c.specs) {
      const s = Object.entries(c.specs).map(([k, v]) => `${k}: ${v}`).join('  |  ');
      lines.push(`  Specs: ${s}`);
    }
    lines.push('');
  }
  if (total > 0) {
    lines.push('──────────────────────────────────────');
    lines.push(`  ESTIMATED TOTAL: $${total.toLocaleString()}`);
    lines.push('──────────────────────────────────────');
  }
  lines.push('');
  lines.push('Generated by NeuroBuilds AI — neurobuilds.app');
  return lines.join('\n');
}

// ─── Component config ─────────────────────────────────────────────────────────

const COMPONENT_CONFIG: Record<
  keyof ActiveBuild,
  { label: string; icon: string; accent: string; border: string; bg: string; ring: string }
> = {
  cpu:         { label: 'CPU',         icon: 'memory',          accent: 'text-primary',       border: 'border-primary/25',       bg: 'bg-primary/5',       ring: 'ring-primary/40'        },
  gpu:         { label: 'GPU',         icon: 'videogame_asset',  accent: 'text-accent-purple', border: 'border-accent-purple/25', bg: 'bg-accent-purple/5', ring: 'ring-accent-purple/40'  },
  motherboard: { label: 'MOTHERBOARD', icon: 'developer_board',  accent: 'text-blue-400',      border: 'border-blue-400/25',      bg: 'bg-blue-400/5',      ring: 'ring-blue-400/40'       },
  ram:         { label: 'RAM',         icon: 'storage',          accent: 'text-green-400',     border: 'border-green-400/25',     bg: 'bg-green-400/5',     ring: 'ring-green-400/40'      },
  psu:         { label: 'PSU',         icon: 'bolt',             accent: 'text-yellow-400',    border: 'border-yellow-400/25',    bg: 'bg-yellow-400/5',    ring: 'ring-yellow-400/40'     },
};

// ─── Power Speedometer ────────────────────────────────────────────────────────

function PowerSpeedometer({ activeBuild }: { activeBuild: ActiveBuild }) {
  const cpuTdp = activeBuild.cpu?.tdp;
  const gpuTdp = activeBuild.gpu?.tdp;
  const psuRating = activeBuild.psu?.rating;

  if (cpuTdp === undefined || gpuTdp === undefined || psuRating === undefined) {
    return (
      <div className="flex flex-col items-center justify-center py-10 gap-3">
        <span className="material-symbols-outlined text-5xl text-gray-700">bolt</span>
        <p className="text-[10px] font-mono text-gray-600 text-center leading-5">
          CPU · GPU · PSU wattage<br />required for power analysis
        </p>
      </div>
    );
  }

  const required = cpuTdp + gpuTdp + 150;
  const loadFraction = required / psuRating;
  const clampedFraction = Math.min(loadFraction, 1);

  // SVG semicircular arc: center (100, 110), radius 80
  // Fraction 0 = left point (20, 110), Fraction 1 = right point (180, 110)
  const cx = 100, cy = 110, r = 80;

  const fractionToXY = (frac: number) => {
    const angleDeg = 180 - frac * 180;
    const angleRad = (angleDeg * Math.PI) / 180;
    return { x: cx + r * Math.cos(angleRad), y: cy - r * Math.sin(angleRad) };
  };

  const startPt = fractionToXY(0);
  const endPt   = fractionToXY(1);
  const fillPt  = fractionToXY(clampedFraction);
  const largeArc = clampedFraction > 0.5 ? 1 : 0;

  const bgPath   = `M ${startPt.x} ${startPt.y} A ${r} ${r} 0 0 1 ${endPt.x} ${endPt.y}`;
  const fillPath = `M ${startPt.x} ${startPt.y} A ${r} ${r} 0 ${largeArc} 1 ${fillPt.x} ${fillPt.y}`;

  const color  = loadFraction < 0.8 ? '#22c55e' : loadFraction < 1.0 ? '#f59e0b' : '#ef4444';
  const isOver = loadFraction > 1.0;
  const isNear = !isOver && loadFraction >= 0.8;

  return (
    <div className="flex flex-col items-center gap-5">
      <svg viewBox="0 0 200 125" className="w-full">
        {/* Background track */}
        <path d={bgPath} fill="none" stroke="#222" strokeWidth="14" strokeLinecap="round" />

        {/* Coloured fill arc */}
        {clampedFraction > 0.005 && (
          <path
            d={fillPath}
            fill="none"
            stroke={color}
            strokeWidth="14"
            strokeLinecap="round"
            style={{ filter: `drop-shadow(0 0 8px ${color}88)` }}
          />
        )}

        {/* Zone tick marks at 80% and 100% */}
        {[0.8, 1.0].map(frac => (
          <line
            key={frac}
            x1={cx + (r - 8) * Math.cos(((180 - frac * 180) * Math.PI) / 180)}
            y1={cy - (r - 8) * Math.sin(((180 - frac * 180) * Math.PI) / 180)}
            x2={cx + (r + 8) * Math.cos(((180 - frac * 180) * Math.PI) / 180)}
            y2={cy - (r + 8) * Math.sin(((180 - frac * 180) * Math.PI) / 180)}
            stroke={frac === 0.8 ? '#f59e0b44' : '#ef444444'}
            strokeWidth="2"
            strokeLinecap="round"
          />
        ))}

        {/* Needle */}
        <line
          x1={cx} y1={cy}
          x2={fillPt.x} y2={fillPt.y}
          stroke={color}
          strokeWidth="2.5"
          strokeLinecap="round"
          style={{ filter: `drop-shadow(0 0 4px ${color})` }}
        />

        {/* Hub */}
        <circle cx={cx} cy={cy} r="6" fill={color} style={{ filter: `drop-shadow(0 0 8px ${color})` }} />

        {/* Load % label */}
        <text x={cx} y={cy - 22} textAnchor="middle" fill={color} fontSize="24" fontWeight="bold" fontFamily="monospace">
          {Math.round(loadFraction * 100)}%
        </text>
        <text x={cx} y={cy - 8} textAnchor="middle" fill="#4b5563" fontSize="8" fontFamily="monospace" letterSpacing="2">
          PSU_LOAD
        </text>

        {/* Scale labels */}
        <text x="12"  y="122" fill="#374151" fontSize="8" fontFamily="monospace">0W</text>
        <text x="84"  y="24"  fill="#374151" fontSize="8" fontFamily="monospace">50%</text>
        <text x="188" y="122" fill="#374151" fontSize="8" fontFamily="monospace" textAnchor="end">{psuRating}W</text>
      </svg>

      {/* Status badge */}
      <div
        className={`w-full rounded-xl px-5 py-4 border text-center ${
          isOver
            ? 'border-red-500/40 bg-red-500/5'
            : isNear
            ? 'border-amber-500/40 bg-amber-500/5'
            : 'border-green-500/40 bg-green-500/5 shadow-[0_0_16px_rgba(34,197,94,0.08)]'
        }`}
      >
        <p className={`text-[11px] font-mono font-bold tracking-widest mb-1.5 ${
          isOver ? 'text-red-400 animate-pulse' : isNear ? 'text-amber-400' : 'text-green-400'
        }`}>
          {isOver ? '⚠  PSU OVERLOADED' : isNear ? '⚡  NEAR CAPACITY' : '✓  POWER BUDGET SAFE'}
        </p>
        <p className="text-[10px] font-mono text-gray-500 leading-5">
          {required}W required · {psuRating}W rated<br />
          ({cpuTdp}W CPU + {gpuTdp}W GPU + 150W buffer)
        </p>
        {isOver && (
          <p className="text-[10px] font-mono text-red-400 mt-2">
            Needs {required - psuRating}W additional headroom
          </p>
        )}
      </div>
    </div>
  );
}

// ─── Component Detail Modal ───────────────────────────────────────────────────

interface ModalProps {
  slot: keyof ActiveBuild;
  component: BuildComponent;
  onClose: () => void;
}

function ComponentDetailModal({ slot, component, onClose }: ModalProps) {
  const cfg = COMPONENT_CONFIG[slot];

  const [dbSpecs, setDbSpecs]       = useState<Record<string, string> | null>(null);
  const [lookupLoading, setLookupLoading] = useState(true);
  const [verifiedBy, setVerifiedBy] = useState<VerificationSource>('ai');

  useEffect(() => {
    const serviceUrl =
      (import.meta.env.VITE_AI_SERVICE_URL as string | undefined) ?? 'http://localhost:8000';
    const controller = new AbortController();

    fetch(
      `${serviceUrl}/api/hardware/lookup?name=${encodeURIComponent(component.name)}`,
      { signal: controller.signal },
    )
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<DbLookupResult>;
      })
      .then(data => {
        // Normalise all spec values to strings for uniform rendering
        const normalised = Object.fromEntries(
          Object.entries(data.specs).map(([k, v]) => [k, String(v)]),
        );
        setDbSpecs(normalised);
        setVerifiedBy('db');
      })
      .catch(() => {
        // Fall back silently to AI-provided specs
        setVerifiedBy('ai');
      })
      .finally(() => setLookupLoading(false));

    return () => controller.abort();
  }, [component.name]);

  // Prefer authoritative DB specs; fall back to AI-extracted component.specs
  const displaySpecs: [string, string][] = dbSpecs
    ? Object.entries(dbSpecs)
    : component.specs ? Object.entries(component.specs) : [];

  const ytQuery = encodeURIComponent(`${component.name} review gamers nexus hardware unboxed`);
  const ytUrl   = `https://www.youtube.com/results?search_query=${ytQuery}`;

  return (
    /* Overlay */
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm"
      onClick={onClose}
    >
      {/* Card — stops click propagation so clicking inside doesn't close */}
      <div
        className="glass-panel rounded-bento border border-white/10 w-full max-w-lg max-h-[90vh] overflow-y-auto shadow-2xl"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className={`flex items-start justify-between p-6 border-b border-white/5 ${cfg.bg}`}>
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 rounded-xl flex items-center justify-center border ${cfg.border} ${cfg.bg}`}>
              <span className={`material-symbols-outlined text-xl ${cfg.accent}`}>{cfg.icon}</span>
            </div>
            <div>
              <p className={`text-[9px] font-mono font-bold tracking-[0.18em] ${cfg.accent}`}>{cfg.label}</p>
              <p className="text-base font-bold text-white leading-snug line-clamp-2">{component.name}</p>
            </div>
          </div>
          <div className="flex items-center gap-3 shrink-0 ml-3">
            {component.price !== undefined && (
              <span className="text-lg font-mono font-bold text-white">${component.price.toLocaleString()}</span>
            )}
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg flex items-center justify-center hover:bg-white/10 text-gray-500 hover:text-white transition-colors"
            >
              <span className="material-symbols-outlined text-lg">close</span>
            </button>
          </div>
        </div>

        <div className="p-6 space-y-6">
          {/* Power badge */}
          {(component.tdp !== undefined || component.rating !== undefined) && (
            <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg border ${cfg.border} ${cfg.bg}`}>
              <span className="material-symbols-outlined text-sm text-yellow-400">bolt</span>
              <span className="text-[10px] font-mono text-gray-300">
                {component.tdp !== undefined ? `${component.tdp}W TDP` : `${component.rating}W Rated`}
              </span>
            </div>
          )}

          {/* Full spec sheet */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <p className="text-[9px] font-mono font-bold text-gray-500 tracking-[0.18em]">SPECIFICATIONS</p>
              {!lookupLoading && (
                <span className={`text-[9px] font-mono px-2 py-0.5 rounded border ${
                  verifiedBy === 'db'
                    ? 'border-primary/40 bg-primary/10 text-primary'
                    : 'border-yellow-400/30 bg-yellow-400/5 text-yellow-500'
                }`}>
                  {verifiedBy === 'db' ? '✓ NeuroBuilds DB' : '~ Verified via AI'}
                </span>
              )}
            </div>

            {lookupLoading ? (
              /* Skeleton rows while the lookup resolves */
              <div className="space-y-2">
                {[0, 1, 2, 3].map(i => (
                  <div key={i} className="h-6 rounded-lg bg-white/5 animate-pulse" />
                ))}
              </div>
            ) : displaySpecs.length > 0 ? (
              <div className="space-y-2">
                {displaySpecs.map(([k, v]) => (
                  <div key={k} className="flex items-baseline justify-between gap-4 py-1.5 border-b border-white/5 last:border-0">
                    <span className="text-[10px] font-mono text-gray-500 capitalize shrink-0">{k.replace(/_/g, ' ')}</span>
                    <span className="text-[10px] font-mono text-gray-200 text-right">{v}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-[10px] font-mono text-gray-600">No specification data available.</p>
            )}
          </div>

          {/* YouTube review tile */}
          <div>
            <p className="text-[9px] font-mono font-bold text-gray-500 tracking-[0.18em] mb-3">VIDEO_REVIEW</p>
            <a
              href={ytUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-4 p-4 rounded-xl border border-white/8 bg-white/3 hover:bg-white/8 hover:border-white/15 transition-all group"
            >
              {/* Faux thumbnail */}
              <div className="w-20 h-14 rounded-lg bg-black/60 border border-white/10 flex items-center justify-center shrink-0 group-hover:border-red-500/40 transition-colors">
                <span className="material-symbols-outlined text-2xl text-red-500/70 group-hover:text-red-500 transition-colors">play_circle</span>
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-gray-200 group-hover:text-white transition-colors line-clamp-2 leading-snug">
                  {component.name} — Full Review &amp; Benchmarks
                </p>
                <p className="text-[9px] font-mono text-gray-600 mt-1">Gamers Nexus · Hardware Unboxed · LTT</p>
              </div>
              <span className="material-symbols-outlined text-gray-600 group-hover:text-white text-sm transition-colors shrink-0">open_in_new</span>
            </a>
          </div>

          {/* Action links */}
          <div className="flex gap-3 pt-1">
            <a
              href={`https://pcpartpicker.com/search/#h=${encodeURIComponent(component.name)}`}
              target="_blank"
              rel="noopener noreferrer"
              className={`flex-1 py-2.5 rounded-xl border text-center text-[10px] font-mono font-bold tracking-widest transition-all hover:opacity-90 ${cfg.border} ${cfg.bg} ${cfg.accent}`}
            >
              PCPartPicker
            </a>
            <button
              onClick={onClose}
              className="flex-1 py-2.5 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 text-center text-[10px] font-mono font-bold tracking-widest text-gray-400 hover:text-white transition-all"
            >
              CLOSE
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Component Card ───────────────────────────────────────────────────────────

function ComponentCard({
  slot,
  component,
  onClick,
}: {
  slot: keyof ActiveBuild;
  component: BuildComponent;
  onClick: () => void;
}) {
  const cfg = COMPONENT_CONFIG[slot];
  const specEntries = component.specs ? Object.entries(component.specs).slice(0, 4) : [];

  return (
    <button
      onClick={onClick}
      className={`w-full text-left rounded-2xl p-5 border overflow-hidden transition-all cursor-pointer
        hover:scale-[1.02] hover:shadow-lg focus-visible:outline-none focus-visible:ring-2
        ${cfg.border} ${cfg.bg} ${cfg.ring}`}
    >
      {/* Top row: icon + label + price */}
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-2">
          <span className={`material-symbols-outlined text-xl leading-none ${cfg.accent}`}>{cfg.icon}</span>
          <span className={`text-[9px] font-bold tracking-[0.18em] font-mono ${cfg.accent}`}>{cfg.label}</span>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          {component.price !== undefined && (
            <span className="text-sm font-mono font-bold text-white">${component.price.toLocaleString()}</span>
          )}
          <span className="material-symbols-outlined text-[14px] text-gray-600">chevron_right</span>
        </div>
      </div>

      {/* Component name — capped at 2 lines */}
      <p className="text-base font-semibold text-white leading-snug mb-3 line-clamp-2">{component.name}</p>

      {/* Spec chips */}
      {specEntries.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-3">
          {specEntries.map(([, v]) => (
            <span
              key={v}
              className="text-[9px] font-mono px-2 py-0.5 rounded-md bg-black/30 border border-white/8 text-gray-400"
            >
              {v}
            </span>
          ))}
        </div>
      )}

      {/* Power stat inline */}
      {(component.tdp !== undefined || component.rating !== undefined) && (
        <p className="text-[9px] font-mono text-gray-600 mt-1">
          {component.tdp !== undefined ? `${component.tdp}W TDP` : `${component.rating}W rated`}
        </p>
      )}

      {/* Click hint */}
      <p className="text-[9px] font-mono text-gray-700 mt-3 flex items-center gap-1">
        <span className="material-symbols-outlined text-[11px]">touch_app</span>
        Tap for specs &amp; review
      </p>
    </button>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

const COMPONENT_ORDER: (keyof ActiveBuild)[] = ['cpu', 'gpu', 'motherboard', 'ram', 'psu'];

export default function SharedBuildPage() {
  const [params]       = useSearchParams();
  const [copied, setCopied]           = useState(false);
  const [selectedSlot, setSelectedSlot] = useState<keyof ActiveBuild | null>(null);

  const activeBuild = decodeBuild(params.get('build'));

  // ── Error / empty state ──────────────────────────────────────────────────────
  if (!activeBuild || !Object.values(activeBuild).some(Boolean)) {
    return (
      <div className="min-h-screen bg-[#0a0a0f] flex flex-col items-center justify-center gap-6 px-4">
        <div className="absolute inset-0 scanline pointer-events-none opacity-20" />
        <span className="material-symbols-outlined text-7xl text-gray-800">link_off</span>
        <div className="text-center">
          <p className="font-mono text-white font-bold text-xl tracking-wider mb-2">INVALID BUILD LINK</p>
          <p className="font-mono text-gray-500 text-sm">
            This share link is missing or the build data is corrupted.
          </p>
        </div>
        <Link
          to="/chat"
          className="px-6 py-3 rounded-pill bg-primary hover:bg-cyan-300 text-black font-bold text-sm tracking-widest transition-colors shadow-[0_0_20px_rgba(13,242,242,0.3)]"
        >
          Open AI Builder
        </Link>
      </div>
    );
  }

  // ── Derived values ───────────────────────────────────────────────────────────
  const totalCost = COMPONENT_ORDER.reduce(
    (sum, key) => sum + (activeBuild[key]?.price ?? 0),
    0,
  );

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildToText(activeBuild));
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const selectedComponent = selectedSlot ? activeBuild[selectedSlot] : null;

  // ── Render ───────────────────────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-[#0a0a0f] relative overflow-x-hidden">
      {/* Ambient gradient blobs */}
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute -top-60 -left-60 w-[600px] h-[600px] rounded-full bg-accent-purple/5 blur-[120px]" />
        <div className="absolute -bottom-60 -right-60 w-[600px] h-[600px] rounded-full bg-primary/5 blur-[120px]" />
      </div>

      {/* Scanline overlay */}
      <div className="pointer-events-none fixed inset-0 scanline opacity-20 z-10" />

      <div className="relative z-20 max-w-6xl mx-auto px-4 sm:px-6 py-10 sm:py-14">

        {/* ── Header ─────────────────────────────────────────────────────────── */}
        <header className="mb-10">
          <div className="flex items-center gap-3 mb-4">
            <span className="material-symbols-outlined text-primary text-2xl">terminal</span>
            <span className="font-bold text-white text-lg tracking-tight">NEURO BUILDS</span>
            <span className="text-gray-700 font-mono text-xs">/</span>
            <span className="text-[10px] font-mono text-gray-500 tracking-widest">SHARED_BUILD</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white leading-tight mb-2">
            PC Build{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent-purple">
              Configuration
            </span>
          </h1>
          <p className="text-sm font-mono text-gray-500">
            Generated by NeuroBuilds AI ·{' '}
            {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </header>

        {/* ── Main grid ──────────────────────────────────────────────────────── */}
        <div className="flex flex-col lg:flex-row gap-6 items-start">

          {/* Left — component cards */}
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-4">
              <span className="material-symbols-outlined text-sm text-gray-500">precision_manufacturing</span>
              <h2 className="text-[10px] font-mono font-bold text-gray-500 tracking-[0.18em]">
                COMPONENTS · click a card for details
              </h2>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {COMPONENT_ORDER.map(key => {
                const c = activeBuild[key];
                if (!c) return null;
                return (
                  <ComponentCard
                    key={key}
                    slot={key}
                    component={c}
                    onClick={() => setSelectedSlot(key)}
                  />
                );
              })}
            </div>
          </div>

          {/* Right — power analysis + cost (sticky on desktop) */}
          <div className="w-full lg:w-80 shrink-0 flex flex-col gap-4 lg:sticky lg:top-6 lg:self-start">

            {/* Power panel */}
            <div className="glass-panel rounded-bento p-6 border border-white/5">
              <div className="flex items-center gap-2 mb-5">
                <span className="material-symbols-outlined text-sm text-yellow-400">bolt</span>
                <h2 className="text-[10px] font-mono font-bold text-gray-500 tracking-[0.18em]">
                  POWER_ANALYSIS
                </h2>
              </div>
              <PowerSpeedometer activeBuild={activeBuild} />
            </div>

            {/* Total cost panel */}
            {totalCost > 0 && (
              <div className="glass-panel rounded-bento px-6 py-5 border border-white/5">
                <p className="text-[10px] font-mono text-gray-500 tracking-widest mb-2">
                  ESTIMATED_TOTAL
                </p>
                <p className="text-3xl font-mono font-bold text-white tracking-tight">
                  ${totalCost.toLocaleString()}
                  <span className="text-sm text-gray-600 font-normal ml-1">USD</span>
                </p>
                <p className="text-[9px] font-mono text-gray-700 mt-1">
                  Prices are AI estimates · verify before purchase
                </p>
              </div>
            )}

            {/* Action buttons */}
            <div className="flex flex-col gap-2">
              <button
                onClick={handleCopy}
                className="w-full py-3 rounded-xl border border-accent-purple/40 bg-accent-purple/10 hover:bg-accent-purple/20 text-white text-[11px] font-mono font-bold tracking-widest flex items-center justify-center gap-2 transition-all hover:shadow-[0_0_16px_rgba(191,0,255,0.25)]"
              >
                <span className="material-symbols-outlined text-sm">
                  {copied ? 'check_circle' : 'content_copy'}
                </span>
                {copied ? 'COPIED!' : 'COPY BUILD LIST'}
              </button>

              <Link
                to="/chat"
                className="w-full py-3 rounded-xl border border-primary/40 bg-primary/10 hover:bg-primary/20 text-primary hover:text-white text-[11px] font-mono font-bold tracking-widest flex items-center justify-center gap-2 transition-all hover:shadow-[0_0_16px_rgba(13,242,242,0.2)]"
              >
                <span className="material-symbols-outlined text-sm">smart_toy</span>
                BUILD WITH NEURO AI
              </Link>
            </div>
          </div>
        </div>

        {/* ── Footer ─────────────────────────────────────────────────────────── */}
        <footer className="mt-12 pt-6 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-primary text-sm">terminal</span>
            <span className="text-xs font-mono text-gray-600">NEUROBUILDS · AI-Assisted PC Build Framework</span>
          </div>
          <p className="text-[10px] font-mono text-gray-700">
            Shared builds are read-only snapshots · Data may not reflect current market prices
          </p>
        </footer>
      </div>

      {/* ── Component Detail Modal ──────────────────────────────────────────── */}
      {selectedSlot && selectedComponent && (
        <ComponentDetailModal
          slot={selectedSlot}
          component={selectedComponent}
          onClose={() => setSelectedSlot(null)}
        />
      )}
    </div>
  );
}
